micronaut:
  application:
    name: guide
  server:
    ssl:
      enabled: 'true'
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
netty:
  default:
    allocator:
      max-order: 3
flyway:
  datasources:
    default:
      enabled: true
azure:
  cosmos:
    consistency-level: SESSION
    default-gateway-mode: true
    endpoint-discovery-enabled: false
    database:
      database-name: myDb
      update-policy: NONE
acme:
  enabled: 'true'
  tos-agree: 'true'
elasticsearch.httpHosts: http://localhost:9200,http://127.0.0.2:9200
